model_list:

  # SCOUT MODEL

  - model_name: berlin-scout-model
    litellm_params:
      model: gemini/gemini-2.0-flash
      api_key: os.environ/GOOGLE_API_KEY

  - model_name: berlin-scout-model
    litellm_params:
      model: groq/llama-3.3-70b-versatile
      api_key: os.environ/GROQ_API_KEY

  - model_name: berlin-scout-model
    litellm_params:
      model: openrouter/meta-llama/llama-3.1-8b-instruct
      api_key: os.environ/OPENROUTER_API_KEY

  - model_name: berlin-scout-model
    litellm_params:
      model: cerebras/llama3.1-8b
      api_key: os.environ/CEREBRAS_API_KEY

  - model_name: berlin-scout-model
    litellm_params:
      model: sambanova/Meta-Llama-3.1-8B-Instruct
      api_key: os.environ/SAMBANOVA_API_KEY


  # CREW MODEL (DEEP REASONING)

  - model_name: berlin-crew-model
    litellm_params:
      model: groq/llama-3.3-70b-versatile
      api_key: os.environ/GROQ_API_KEY

  - model_name: berlin-crew-model
    litellm_params:
      model: openrouter/meta-llama/llama-3.1-70b-instruct
      api_key: os.environ/OPENROUTER_API_KEY

  - model_name: berlin-crew-model
    litellm_params:
      model: gemini/gemini-2.0-flash
      api_key: os.environ/GOOGLE_API_KEY

  - model_name: berlin-crew-model
    litellm_params:
      model: cerebras/llama3.1-8b
      api_key: os.environ/CEREBRAS_API_KEY

  - model_name: berlin-crew-model
    litellm_params:
      model: sambanova/Meta-Llama-3.1-8B-Instruct
      api_key: os.environ/SAMBANOVA_API_KEY


  # DEEPEVAL MODEL (QUALITY JUDGE)
  - model_name: quality-judge
    litellm_params:
      model: cerebras/llama3.1-8b
      api_key: os.environ/CEREBRAS_API_KEY

  - model_name: quality-judge
    litellm_params:
      model: groq/llama-3.3-70b-versatile
      api_key: os.environ/GROQ_API_KEY

  - model_name: quality-judge
    litellm_params:
      model: gemini/gemini-2.0-flash
      api_key: os.environ/GOOGLE_API_KEY

  - model_name: quality-judge
    litellm_params:
      model: openrouter/meta-llama/llama-3.1-8b-instruct
      api_key: os.environ/OPENROUTER_API_KEY

  - model_name: quality-judge
    litellm_params:
      model: sambanova/Meta-Llama-3.1-8B-Instruct
      api_key: os.environ/SAMBANOVA_API_KEY

      

router_settings:
  routing_strategy: simple-shuffle
  num_retries: 4
  cooldown_time: 1
  fallbacks: 
    - {"berlin-scout-model": ["berlin-crew-model"]}
  enable_pre_call_check: true
  set_verbose: true

general_settings:
  master_key: sk-1234 # internal "admin" key for the proxy

litellm_settings:
  request_timeout: 20